# Service Configuration
version=1.0.0
threads=5
# Island
island.width=2
island.height=2
island.tick=1000
island.maxsimpletick=10
# init
init.animal=bear:10;boa:5;bull:8;deer:8;duck:10;eagle:6;fox:6;goat:6;horse:9;mouse:15;rabbit:15;sheep:12;wildboar:10;wolf:6;worm:25
init.plant=200
# Plant
plant.maxcount=200
plant.weight=1.00
plant.percell=200
# Animals
# wolf
wolf.name=????
wolf.weight=50
wolf.maxcount=30
wolf.jump=3
wolf.eat=8
wolf.eatlist=horse:10;deer:15;rabbit:60;mouse:80;goat:60;sheep:70;wildboar:15;bull:10;duck:40
wolf.gender=true
wolf.reproduction=50
# boa
boa.name=????
boa.weight=15
boa.maxcount=30
boa.jump=1
boa.eat=3
boa.eatlist=fox:15;rabbit:20;mouse:40;duck:10
boa.gender=true
boa.reproduction=50
# fox
fox.name=????
fox.weight=8
fox.maxcount=30
fox.jump=2
fox.eat=2
fox.eatlist=rabbit:70;mouse:90;duck:60;worm:40
fox.gender=true
fox.reproduction=50
# bear
bear.name=???????
bear.weight=500
bear.maxcount=5
bear.jump=2
bear.eat=80
bear.eatlist=boa:80;horse:40;deer:80;rabbit:80;mouse:90;goat:70;sheep:70;wildboar:50;bull:20;duck:10
bear.gender=true
bear.reproduction=50
# eagle
eagle.name=????
eagle.weight=6
eagle.maxcount=20
eagle.jump=3
eagle.eat=1
eagle.eatlist=fox:10;rabbit:90;mouse:90;duck:80
eagle.gender=true
eagle.reproduction=50
# horse
horse.name=??????
horse.weight=400
horse.maxcount=20
horse.jump=4
horse.eat=60
horse.eatlist=plant:100
horse.gender=true
horse.reproduction=50
# deer
deer.name=?????
deer.weight=300
deer.maxcount=20
deer.jump=4
deer.eat=50
deer.eatlist=plant:100
deer.gender=true
deer.reproduction=50
# rabbit
rabbit.name=??????
rabbit.weight=2
rabbit.maxcount=150
rabbit.jump=2
rabbit.eat=0.45
rabbit.eatlist=plant:100
rabbit.gender=true
rabbit.reproduction=50
# mouse
mouse.name=????
mouse.weight=0.05
mouse.maxcount=500
mouse.jump=1
mouse.eat=0.01
mouse.eatlist=worm:90;plant:100
mouse.gender=true
mouse.reproduction=50
# goat
goat.name=????
goat.weight=60
goat.maxcount=140
goat.jump=3
goat.eat=10
goat.eatlist=plant:100
goat.gender=true
goat.reproduction=50
# sheep
sheep.name=????
sheep.weight=70
sheep.maxcount=140
sheep.jump=3
sheep.eat=15
sheep.eatlist=plant:100
sheep.gender=true
sheep.reproduction=50
# wildboar
wildboar.name=?????
wildboar.weight=400
wildboar.maxcount=50
wildboar.jump=2
wildboar.eat=50
wildboar.eatlist=mouse:50;worm:90;plant:100
wildboar.gender=true
wildboar.reproduction=50
# bull
bull.name=??????
bull.weight=700
bull.maxcount=10
bull.jump=3
bull.eat=100
bull.eatlist=plant:100
bull.gender=true
bull.reproduction=50
# duck
duck.name=????
duck.weight=1
duck.maxcount=200
duck.jump=4
duck.eat=0.15
duck.eatlist=worm:90;plant:100
duck.gender=true
duck.reproduction=50
# worm
worm.mame=????????
worm.weight=0.01
worm.maxcount=1000
worm.jump=0
worm.eat=0
worm.eatlist=plant:100
worm.gender=false
worm.reproduction=50